% define colors for listings
\definecolor{old-background}{rgb}{0.95,0.95,0.92}

% colors of github light theme
\definecolor{ghl-background}{rgb}{1,1,1}
\definecolor{ghl-basic}{rgb}{0.1411764705882353,0.1607843137254902,0.1803921568627451}
\definecolor{ghl-comment}{rgb}{0.41568627450980394,0.45098039215686275,0.49019607843137253}
\definecolor{ghl-keyword}{rgb}{0.8431372549019608,0.22745098039215686,0.28627450980392155}
\definecolor{ghl-linenumber}{rgb}{0.7294117647058823,0.7333333333333333,0.7411764705882353}
\definecolor{ghl-string}{rgb}{0.011764705882352941,0.1843137254901961,0.3843137254901961}

% colors of github dark theme
\definecolor{ghd-background}{rgb}{0.1411764705882353, 0.1607843137254902, 0.1803921568627451}
\definecolor{ghd-basic}{rgb}{0.8823529411764706,0.8941176470588236,0.9098039215686274}
\definecolor{ghd-comment}{rgb}{0.41568627450980394,0.45098039215686275,0.49019607843137253}
\definecolor{ghd-keyword}{rgb}{0.9764705882352941,0.4588235294117647,0.5137254901960784}
\definecolor{ghd-linenumber}{rgb}{0.26666666666666666,0.30196078431372547,0.33725490196078434}
\definecolor{ghd-string}{rgb}{0.6196078431372549,0.796078431372549,1}

% supported languages can be found here: https://de.overleaf.com/learn/latex/Code_listing#Supported_languages
% or here: https://mirror.funkfreundelandshut.de/latex/macros/latex/contrib/listings/listings.pdf on page 13

% github light theme
\lstdefinestyle{github-light}{
    backgroundcolor=\color{ghl-background},     % choose the background color
    basicstyle=\ttfamily\footnotesize,          % the size of the fonts that are used for the code
    breakatwhitespace=false,                    % sets if automatic breaks should only happen at whitespace
    breaklines=true,                            % sets automatic line breaking
    captionpos=b,                               % sets the caption-position to bottom
    commentstyle=\color{ghl-comment},           % comment style
    deletekeywords={...},                       % if you want to delete keywords from the given language
    escapeinside={\%*}{*)},                     % if you want to add LaTeX within your code
    extendedchars=true,                         % lets you use non-ASCII characters; for 8-bits encodings only, does not work with UTF-8
    firstnumber=1,                              % start line enumeration with line 1
    frame=single,                               % adds a frame around the code
    keepspaces=true,                            % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{ghl-keyword},           % keyword style
    language=Octave,                            % the language of the code
    morekeywords={*,...},                       % if you want to add more keywords to the set
    numbers=left,                               % where to put the line-numbers; possible values are (none, left, right)
    numbersep=5pt,                              % how far the line-numbers are from the code
    numberstyle=\tiny\color{ghl-linenumber},    % the style that is used for the line-numbers
    rulecolor=\color{black},                    % if not set, the frame-color may be changed on line-breaks within not-black text (e.g. comments (green here))
    showspaces=false,                           % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,                     % underline spaces within strings only
    showtabs=false,                             % show tabs within strings adding particular underscores
    stepnumber=1,                               % the step between two line-numbers. If it's 1, each line will be numbered
    stringstyle=\color{ghl-string},             % string literal style
    tabsize=2,                                  % sets default tabsize to 2 spaces
}

% github dark theme
\lstdefinestyle{github-dark}{
    backgroundcolor=\color{ghd-background},
    basicstyle=\ttfamily\footnotesize,
    breakatwhitespace=false,
    breaklines=true,
    captionpos=b,
    commentstyle=\color{ghd-comment},
    deletekeywords={...},
    escapeinside={\%*}{*)},
    extendedchars=true,
    firstnumber=0,
    frame=single,
    keepspaces=true,
    keywordstyle=\color{ghd-keyword},
    language=Octave,
    morekeywords={*,...},
    numbers=left,
    numbersep=5pt,
    numberstyle=\tiny\color{ghd-linenumber},
    rulecolor=\color{black},
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    stepnumber=1,
    stringstyle=\color{ghd-string},
    tabsize=2,
}
